/**
* This file was auto-generated by SAP Web IDE build and includes all
* the source files required by SAPUI5 runtime for performance optimization.
* PLEASE DO NOT EDIT THIS FILE!! Changes will be overwritten the next time the build is run.
*/
jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "rmch/Component-preload",
	"modules": {
		"rmch/view/View.view.xml": "<mvc:View controllerName=\"rmch.controller.View\" xmlns:html=\"http://www.w3.org/1999/xhtml\" xmlns:mvc=\"sap.ui.core.mvc\" xmlns=\"sap.m\">\n\t<App>\n\t\t<pages>\n\t\t\t<Page title=\"{i18n>title}\">\n\t\t\t\t<content>\n\t\t\t\t\t<StandardTile title=\"RMC-HANA LINK\" info=\"Info\" icon=\"sap-icon://customer\" activeIcon=\"sap-icon://customer\" number=\"12\" numberUnit=\"eur\" infoState=\"Success\" id=\"__tile0\" press=\"onClick\"/>\n\t\t\t\t</content>\n\t\t\t</Page>\n\t\t</pages>\n\t</App>\n</mvc:View>",
		"rmch/controller/View.controller.js": "sap.ui.define([\n\t\"sap/ui/core/mvc/Controller\"\n], function(Controller) {\n\t\"use strict\";\n\n\treturn Controller.extend(\"rmch.controller.View\", {\n\t\tonClick: function() {\n\t\t\t//This code was generated by the layout editor.\n\t\t\t//\twindow.open('http://help.sap.com/','_blank','toolbar=0,location=0,menubar=0');\n\t\t\t//window.open('https://10.11.7.45/rmc-ui/#/login','_blank','toolbar=0,location=0,menubar=0');\n\t\t\t$.get(\"rmcIP.json\", function(data) {\n\t\t\t\t//  var dataIp = $.parseJSON(data);\n\t\t\t\t//   var dataIp = $.parseJSON(data);\n\t\t\t\twindow.open('https://' + data.id + '/rmc-ui/#/login', '_blank', 'toolbar=0,location=0,menubar=0');\n\t\t\t});\n\t\t}\n\n\t});\n\n});",
		"rmch/model/models.js": "sap.ui.define([\n\t\"sap/ui/model/json/JSONModel\",\n\t\"sap/ui/Device\"\n], function(JSONModel, Device) {\n\t\"use strict\";\n\n\treturn {\n\n\t\tcreateDeviceModel: function() {\n\t\t\tvar oModel = new JSONModel(Device);\n\t\t\toModel.setDefaultBindingMode(\"OneWay\");\n\t\t\treturn oModel;\n\t\t}\n\n\t};\n\n});",
		"rmch/Component.js": "sap.ui.define([\n\t\"sap/ui/core/UIComponent\",\n\t\"sap/ui/Device\",\n\t\"rmch/model/models\"\n], function(UIComponent, Device, models) {\n\t\"use strict\";\n\n\treturn UIComponent.extend(\"rmch.Component\", {\n\n\t\tmetadata: {\n\t\t\tmanifest: \"json\"\n\t\t},\n\n\t\t/**\n\t\t * The component is initialized by UI5 automatically during the startup of the app and calls the init method once.\n\t\t * @public\n\t\t * @override\n\t\t */\n\t\tinit: function() {\n\t\t\t// call the base component's init function\n\t\t\tUIComponent.prototype.init.apply(this, arguments);\n\n\t\t\t// set the device model\n\t\t\tthis.setModel(models.createDeviceModel(), \"device\");\n\t\t}\n\t});\n\n});"
	}
});